name: Pull request update
on:
    push:
        branches: [main]
jobs:
    autoupdate:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: allonsy-studio/actions-pr-auto-update@v3
